### ISSUE TITLE
Document supported Erlang versions

### ISSUE THREAD

**Issue by edmorley** [heroku/vegur#163]
After cloning the repo, I wasn't sure what version of Erlang to install since the README didn't say.

I spotted `.preferred_otp_version` which lists `OTP_R16B02`, so installed the [Ubuntu Trusty erlang package](http://packages.ubuntu.com/trusty/erlang) which is R16B03 and so seemed close enough.

However that resulted in errors about a missing `priv` directory, and then after manually creating it, still failed with `_build/test/lib/vegur/src/vegur_proxy.erl:none: internal error in lint_module;` etc.

I finally spotted the `.travis.yml` versions and the README changelog reference to `dropping support for OTP 16 and 17`, so switched to OTP 19.1.

I'm presuming `.preferred_otp_version` is a relic and can be removed. In addition, a mention of supported versions in the README compile section (and links to upstream binaries, given Ubuntu's packages are out of date) would be useful :-)

**Comment by dongyuwei** [comment]
I tested it with Erlang/OTP 20 on Ubuntu 18.10,  the `demo/toy_router.erl` works as expected.
