### ISSUE TITLE
Long dead but still used in production?

### ISSUE THREAD

**Issue by hartwork** [heroku/vegur#188]
Hello @heroku,

the last commit in here is 3 years old, the latest Git tag 7 years old, CI seems to be inactive and still using Travis CI, and yet production Heroku says `Via: 1.1 vegur` in HTTP responses while the latest Git tag in here is 2.0.6. If that is a misunderstanding or incomplete picture, it would be great to understand. Thank you!

Best, Sebastian

CC @gbtami

**Comment by ferd** [comment]
My guess as a former employee that left in 2016 and who has no recent information is that they replaced the routing stack by a non-open version but kept the headers the same for backwards compatibility.

It is impressive how small changes would break apps that were hosted on the platform, and I have to imagine they were careful to make an identical match.

**Comment by hartwork** [comment]
@ferd thanks for sharing your view! :+1:

**Comment by hartwork** [comment]
Closing to keep my https://github.com/issues clean…
